### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by crshrprt** [suzumushi0/VoMPE_source#1]
Thank you for this interesting plugin.

I see [CMakeLists.txt](https://github.com/suzumushi0/VoMPE_source/blob/main/CMakeLists.txt) contains only Win and Mac.
Is there any chance for a Linux vst3 version?

**Comment by suzumushi0** [comment]
crshrprt,

I only use the VST3 project generator included in the VST SDK. It generates CMakeLists.txt automatically. The generator supports Win and Mac, but Linux is not supported. I have no experience with Linux VST3, but it seems to me that the following article might be informative for Linux.

https://forums.steinberg.net/t/setting-up-a-new-project-on-linux/792671

**Comment by crshrprt** [comment]
Thank you for the prompt response, after a few tries I manged to compile it on Linux. 
The plugin loads and GUI is shown, I've yet to try if it actually works.
For those interested I had to change the vst3sdk path and add `set(CMAKE_CXX_FLAGS "-std=c++20")` in `CmakeLists.txt` (not sure if the latter is what fixed my compilation errros) but at the end it worked.
